/**************************************************************
   Il programma controlla la temperatura/umidità grazie al sensore DHT11, invia il
   risultato elaborato dalla ESP8266 all'App Blynk.
   
   La funzione "Controlla" controlla lo stato del sensore,
   "sendUptime" invia i dati, ogni secondo, alla ESP8266.

   Git: DaveCalaway
   Tutorial: http://goo.gl/jr78gT

   WARNING :
   Questo esempio utilizza la SimpleTimer library:
     http://playground.arduino.cc/Code/SimpleTimer
   Questo esempio utilizza la dht11 Library:
     http://www.instructables.com/files/orig/FHB/K7SE/IGV8M93S/FHBK7SEIGV8M93S.zip

 **************************************************************/

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h> // Libreria Simple Timer
#include <dht11.h> // Libreria sensore DHT11
#define DHT11_PIN 12 // Pin fisico D6
dht11 DHT;

// You should get Auth Token in the Blynk App.
char auth[] = "Auth Token"; //insert here your token generated by Blynk

SimpleTimer timer;  // Imposto l'uso del timer

void setup() {
  Blynk.begin(auth, " Nome ", " Password "); //Inserie SSID and password della rete

  // Imposta il timer in modo da chiamare la funzione "sendUptime" ogni secondo
  timer.setInterval(1000L, sendUptime);
}

// ------ La funzione invia alla ESP8266 i dati acquisiti dal sensore
void sendUptime() {
  Blynk.virtualWrite(10, DHT.temperature); // Temperatura su Pin Virtuale 10
  Blynk.virtualWrite(11, DHT.humidity); // Umidità su Pin Virtuale 10
}

void loop() {
  Blynk.run(); // Initiates Blynk
  timer.run(); // Initiates SimpleTimer
  int controlla;
  controlla = DHT.read(DHT11_PIN);    // Legge i dati da sensore
}

